name: Build and Push Docker Image

on:
  push:
    paths:
      - 'dockerfile'
      - 'index.html'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository so the workflow can access files
      - uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image to dockerhub
      - name: Build and push Docker image
        run: |
          docker build -t vishaantmatabadal/vashisht:latest .
          docker push vishaantmatabadal/vashisht:latest
